### ISSUE TITLE
LSA Text.ipynb - TruncatedSVD object has no attribute 'components_

### ISSUE THREAD

**Issue by tkyoon21** [mbernico/CS570#1]
Hi!
I'm using LSA Text.ipynb.
But when executing the code
`lsa.components_[0]`
The error message

> AttributeError: 'TruncatedSVD' object has no attribute 'components_'

How can I solve this problem?
I'm using python 2.7 in Anaconda environment, but I tried in Eclipse Pydev, same problem exists.
Here is the code
`# -*- coding: utf-8 -*-`
`from bs4 import BeautifulSoup`
`import nltk`
`from nltk.corpus import stopwords`
`from sklearn.feature_extraction.text import TfidfVectorizer`
`from sklearn.decomposition import TruncatedSVD`
`posts = open('raw_forum_posts.dat','r').read()`
`soup = BeautifulSoup(posts, "lxml")`
`postTxt = soup.findAll('text')`
`postDocs = [x.text for x in postTxt]`
`postDocs.pop(0)`
`postDocs = [x.lower() for x in postDocs]`
`stopset = set(stopwords.words('english'))`
`stopset.update(['lt','p','/p','br','amp','quot','field' ])`
`vectorizer = TfidfVectorizer(stop_words=stopset, use_idf=True, ngram_range=(1, 3))`
`X = vectorizer.fit_transform(postDocs)`
`lsa = TruncatedSVD(n_components=27, n_iter=100)`
`lsa.components_[0]`

**Comment by mbernico** [comment]
I've refactored this into python 3 (Sorry for the delay).   Please try again.

**Comment by janithapm** [comment]
hye what is ithe corpus that u are using in there , meanwhilecan you explain me how to add a corpus of my own

**Comment by mbernico** [comment]
@janithapm The corpus I'm using is the forum posts from the class I teach.   

You can use your own corpus by changing this code
`posts = open('raw_forum_posts.dat','r').read()`

You'll want your data to be in a list, where each element is a document in the corpus.  Good luck!

**Comment by janithapm** [comment]
@mbernico thank you for your help
